[meta]
name = "Split Speeds - Envimix Edition"
author = "RuteNL / Buldy"
category = "Overlay"
version = "1.0"

[script]
dependencies = [ "VehicleState" ]
exports = [ "src/Exports/SplitSpeedsExports.as" ]

